spring:
  application:
    name: enum-pattern
  info:
    build:
      creator: Metehan Gultekin
  datasource:
    url: jdbc:postgresql://localhost:5432/enum_pattern
    username: postgres
    password: toor
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'false'
    hibernate:
      ddl-auto: update

server:
  port: 8089